qubes-rpc-multiplexer: allow to keep RPC scripts in /usr/local
/usr/local resides in private.img, so it is possible to define per-appvm RPC

diff --git a/qrexec/qubes-rpc-multiplexer b/qrexec/qubes-rpc-multiplexer
--- a/qrexec/qubes-rpc-multiplexer
+++ b/qrexec/qubes-rpc-multiplexer
@@ -6,6 +6,7 @@ exec 2>/tmp/qrexec-rpc-stderr.$$
 rm -f /tmp/qrexec-rpc-stderr.$$
 
 QUBES_RPC=/etc/qubes-rpc
+LOCAL_QUBES_RPC=/usr/local/etc/qubes-rpc
 # XXX: Backward compatibility
 DEPRECATED_QUBES_RPC=/etc/qubes_rpc
 if ! [ $# = 2 ] ; then
@@ -13,12 +14,13 @@ if ! [ $# = 2 ] ; then
 	exit 1
 fi
 export QREXEC_REMOTE_DOMAIN="$2"
-CFG_FILE=$QUBES_RPC/"$1"
-if [ -s "$CFG_FILE" ] ; then
-	exec /bin/sh "$CFG_FILE"
-	echo "$0: failed to execute handler for" "$1" >&2
-	exit 1
-fi
+for CFG_FILE in $QUBES_RPC/"$1" $LOCAL_QUBES_RPC/"$1"; do
+	if [ -s "$CFG_FILE" ] ; then
+		exec /bin/sh "$CFG_FILE"
+		echo "$0: failed to execute handler for" "$1" >&2
+		exit 1
+	fi
+done
 CFG_FILE=$DEPRECATED_QUBES_RPC/"$1"
 if [ -s "$CFG_FILE" ] ; then
     echo "$0: RPC service '$1' uses deprecated directory, please move to $QUBES_RPC" >&2
